apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ecommerce-microservices
  description: E-commerce platform built using microservices architecture (Development)
  annotations:
    github.com/project-slug: ANandasaad/ecommerce-microservices
    backstage.io/techdocs-ref: dir:.        # Kubernetes plugin for dev env

spec:
  type: service
  lifecycle: development
  owner: team-ecommerce
